name: dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.14
  - debugpy
  - ipykernel
  - ipython
  - joblib
  - jupyterlab
  - matplotlib
  - mypy
  - nodejs
  - numpy
  - pandas-stubs
  - pandas>=2.0.0
  - poppler
  - pre-commit
  - pydantic
  - pynvim
  - pytest
  - pytest-cov
  - requests
  - ruff
  - scipy
  - seaborn
  - uv
  - yarn
  - pip:
    - ranger-fm
